services:
  client:
    build:
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
  server:
    build:
      target: dev
    volumes:
      - ./server:/app/server
      - ./common:/app/common